"""empty message

Revision ID: fdd58e08209e
Revises: cbb0e48266e6
Create Date: 2024-07-30 16:20:41.487379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdd58e08209e'
down_revision = 'cbb0e48266e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('student_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('student_ibfk_1', type_='foreignkey')
        batch_op.drop_column('subcourse_id')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('subcourse_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('student_ibfk_1', 'course', ['course_id'], ['id'])
        batch_op.create_foreign_key('student_ibfk_2', 'sub_course', ['subcourse_id'], ['id'])

    # ### end Alembic commands ###
